PROVIDERS = {
    # ========== SOSIAL MEDIA (50+) ==========
    "tiktok": {"category": "sosial_media", "method": "email", "target": "report@tiktok.com"},
    "instagram": {"category": "sosial_media", "method": "email", "target": "support@instagram.com"},
    "facebook": {"category": "sosial_media", "method": "email", "target": "abuse@facebook.com"},
    "twitter": {"category": "sosial_media", "method": "email", "target": "safety@twitter.com"},
    "youtube": {"category": "sosial_media", "method": "email", "target": "support@youtube.com"},
    "telegram": {"category": "sosial_media", "method": "email", "target": "abuse@telegram.org"},
    "whatsapp": {"category": "sosial_media", "method": "email", "target": "support@whatsapp.com"},
    "line": {"category": "sosial_media", "method": "email", "target": "support@line.me"},
    "wechat": {"category": "sosial_media", "method": "email", "target": "support@wechat.com"},
    "signal": {"category": "sosial_media", "method": "email", "target": "support@signal.org"},
    "discord": {"category": "sosial_media", "method": "email", "target": "support@discord.com"},
    "reddit": {"category": "sosial_media", "method": "email", "target": "contact@reddit.com"},
    "linkedin": {"category": "sosial_media", "method": "email", "target": "help@linkedin.com"},
    "snapchat": {"category": "sosial_media", "method": "email", "target": "support@snapchat.com"},
    "pinterest": {"category": "sosial_media", "method": "email", "target": "help@pinterest.com"},
    "tumblr": {"category": "sosial_media", "method": "email", "target": "support@tumblr.com"},
    "vk": {"category": "sosial_media", "method": "email", "target": "support@vk.com"},
    "flickr": {"category": "sosial_media", "method": "email", "target": "help@flickr.com"},
    "tinder": {"category": "sosial_media", "method": "email", "target": "support@tinder.com"},
    "bumble": {"category": "sosial_media", "method": "email", "target": "support@bumble.com"},
    "okcupid": {"category": "sosial_media", "method": "email", "target": "support@okcupid.com"},
    "hinge": {"category": "sosial_media", "method": "email", "target": "support@hinge.co"},
    "grindr": {"category": "sosial_media", "method": "email", "target": "support@grindr.com"},
    "meetup": {"category": "sosial_media", "method": "email", "target": "support@meetup.com"},
    "nextdoor": {"category": "sosial_media", "method": "email", "target": "support@nextdoor.com"},
    "periscope": {"category": "sosial_media", "method": "email", "target": "support@periscope.tv"},
    "twitch": {"category": "sosial_media", "method": "email", "target": "support@twitch.tv"},
    "kik": {"category": "sosial_media", "method": "email", "target": "support@kik.com"},
    "imo": {"category": "sosial_media", "method": "email", "target": "support@imo.im"},
    "zalo": {"category": "sosial_media", "method": "email", "target": "support@zalo.me"},
    "viber": {"category": "sosial_media", "method": "email", "target": "support@viber.com"},
    "skype": {"category": "sosial_media", "method": "email", "target": "support@skype.com"},
    "slack": {"category": "sosial_media", "method": "email", "target": "support@slack.com"},
    "microsoft_teams": {"category": "sosial_media", "method": "email", "target": "support@teams.microsoft.com"},
    "zoom": {"category": "sosial_media", "method": "email", "target": "support@zoom.us"},
    "google_meet": {"category": "sosial_media", "method": "email", "target": "support@meet.google.com"},
    "ciscowebex": {"category": "sosial_media", "method": "email", "target": "support@webex.com"},

    # ========== E-COMMERCE INDONESIA (20+) ==========
    "shopee": {"category": "ecommerce", "method": "email", "target": "report@shopee.co.id"},
    "tokopedia": {"category": "ecommerce", "method": "email", "target": "pengaduan@tokopedia.com"},
    "bukalapak": {"category": "ecommerce", "method": "email", "target": "pengaduan@bukalapak.com"},
    "lazada": {"category": "ecommerce", "method": "email", "target": "report@lazada.co.id"},
    "blibli": {"category": "ecommerce", "method": "email", "target": "cs@blibli.com"},
    "jd.id": {"category": "ecommerce", "method": "email", "target": "support@jd.id"},
    "zalora": {"category": "ecommerce", "method": "email", "target": "help@zalora.co.id"},
    "sociolla": {"category": "ecommerce", "method": "email", "target": "customercare@sociolla.com"},
    "oriflame": {"category": "ecommerce", "method": "email", "target": "support@oriflame.co.id"},
    "ruparupa": {"category": "ecommerce", "method": "email", "target": "support@ruparupa.com"},
    "acehardware": {"category": "ecommerce", "method": "email", "target": "customerservice@acehardware.co.id"},
    "informa": {"category": "ecommerce", "method": "email", "target": "cs@informa.co.id"},
    "matahari": {"category": "ecommerce", "method": "email", "target": "cs@matahari.co.id"},
    "evermos": {"category": "ecommerce", "method": "email", "target": "support@evermos.com"},
    "klikindomaret": {"category": "ecommerce", "method": "email", "target": "help@klikindomaret.com"},
    "alfagift": {"category": "ecommerce", "method": "email", "target": "cs@alfagift.com"},
    "sayurbox": {"category": "ecommerce", "method": "email", "target": "help@sayurbox.com"},
    "happyfresh": {"category": "ecommerce", "method": "email", "target": "support@happyfresh.com"},
    "taniHub": {"category": "ecommerce", "method": "email", "target": "support@tanihub.com"},

    # ========== E-COMMERCE INTERNASIONAL (30+) ==========
    "amazon": {"category": "ecommerce_intl", "method": "email", "target": "report-abuse@amazon.com"},
    "ebay": {"category": "ecommerce_intl", "method": "email", "target": "report@ebay.com"},
    "aliexpress": {"category": "ecommerce_intl", "method": "email", "target": "report@aliexpress.com"},
    "wish": {"category": "ecommerce_intl", "method": "email", "target": "support@wish.com"},
    "etsy": {"category": "ecommerce_intl", "method": "email", "target": "help@etsy.com"},
    "alibaba": {"category": "ecommerce_intl", "method": "email", "target": "report@alibaba.com"},
    "jd.com": {"category": "ecommerce_intl", "method": "email", "target": "support@jd.com"},
    "pinduoduo": {"category": "ecommerce_intl", "method": "email", "target": "support@pinduoduo.com"},
    "temu": {"category": "ecommerce_intl", "method": "email", "target": "support@temu.com"},
    "shein": {"category": "ecommerce_intl", "method": "email", "target": "support@shein.com"},
    "zalando": {"category": "ecommerce_intl", "method": "email", "target": "support@zalando.com"},
    "asos": {"category": "ecommerce_intl", "method": "email", "target": "help@asos.com"},
    "farfetch": {"category": "ecommerce_intl", "method": "email", "target": "support@farfetch.com"},
    "shopify": {"category": "ecommerce_intl", "method": "email", "target": "support@shopify.com"},
    "walmart": {"category": "ecommerce_intl", "method": "email", "target": "abuse@walmart.com"},
    "target": {"category": "ecommerce_intl", "method": "email", "target": "support@target.com"},
    "costco": {"category": "ecommerce_intl", "method": "email", "target": "support@costco.com"},
    "bestbuy": {"category": "ecommerce_intl", "method": "email", "target": "support@bestbuy.com"},
    "homedepot": {"category": "ecommerce_intl", "method": "email", "target": "support@homedepot.com"},
    "lowes": {"category": "ecommerce_intl", "method": "email", "target": "support@lowes.com"},
    "macys": {"category": "ecommerce_intl", "method": "email", "target": "support@macys.com"},
    "nordstrom": {"category": "ecommerce_intl", "method": "email", "target": "support@nordstrom.com"},
    "sephora": {"category": "ecommerce_intl", "method": "email", "target": "support@sephora.com"},
    "ul Beauty": {"category": "ecommerce_intl", "method": "email", "target": "support@ulbeauty.com"},
    "kohls": {"category": "ecommerce_intl", "method": "email", "target": "support@kohls.com"},

    # ========== BANK INDONESIA (15+) ==========
    "bri": {"category": "bank", "method": "email", "target": "fraud@bri.co.id"},
    "bca": {"category": "bank", "method": "email", "target": "pengaduan@bca.co.id"},
    "mandiri": {"category": "bank", "method": "email", "target": "callcenter@bankmandiri.co.id"},
    "bni": {"category": "bank", "method": "email", "target": "pengaduan@bni.co.id"},
    "btn": {"category": "bank", "method": "email", "target": "pengaduan@btn.co.id"},
    "cimb": {"category": "bank", "method": "email", "target": "customer.care@cimbniaga.co.id"},
    "danamon": {"category": "bank", "method": "email", "target": "help@danamon.co.id"},
    "permata": {"category": "bank", "method": "email", "target": "callcenter@permatabank.co.id"},
    "maybank": {"category": "bank", "method": "email", "target": "m2u@maybank.co.id"},
    "muamalat": {"category": "bank", "method": "email", "target": "cs@muamalat.co.id"},
    "syariah_mandiri": {"category": "bank", "method": "email", "target": "customercare@bsm.co.id"},
    "bukopin": {"category": "bank", "method": "email", "target": "customerservice@bukopin.co.id"},
    "panin": {"category": "bank", "method": "email", "target": "callcenter@panin.co.id"},
    "ocbc": {"category": "bank", "method": "email", "target": "callcenter@ocbc.id"},
    "mega": {"category": "bank", "method": "email", "target": "customer@megabank.co.id"},
    "sinarmas": {"category": "bank", "method": "email", "target": "cs@sinarmasbank.com"},

    # ========== BANK INTERNASIONAL (20+) ==========
    "hsbc": {"category": "bank_intl", "method": "email", "target": "report.fraud@hsbc.com"},
    "citi": {"category": "bank_intl", "method": "email", "target": "fraudalert@citi.com"},
    "jpmorgan": {"category": "bank_intl", "method": "email", "target": "fraud@jpmorgan.com"},
    "deutsche": {"category": "bank_intl", "method": "email", "target": "fraud@db.com"},
    "barclays": {"category": "bank_intl", "method": "email", "target": "fraud@barclays.com"},
    "standardchartered": {"category": "bank_intl", "method": "email", "target": "fraud@sc.com"},
    "ubs": {"category": "bank_intl", "method": "email", "target": "fraud@ubs.com"},
    "credit_suisse": {"category": "bank_intl", "method": "email", "target": "fraud@credit-suisse.com"},
    "goldman_sachs": {"category": "bank_intl", "method": "email", "target": "fraud@gs.com"},
    "morgan_stanley": {"category": "bank_intl", "method": "email", "target": "fraud@morganstanley.com"},
    "bank_of_america": {"category": "bank_intl", "method": "email", "target": "fraud@bankofamerica.com"},
    "wells_fargo": {"category": "bank_intl", "method": "email", "target": "fraud@wellsfargo.com"},
    "chase": {"category": "bank_intl", "method": "email", "target": "fraud@chase.com"},
    "capital_one": {"category": "bank_intl", "method": "email", "target": "fraud@capitalone.com"},
    "amex": {"category": "bank_intl", "method": "email", "target": "fraud@americanexpress.com"},
    "discover": {"category": "bank_intl", "method": "email", "target": "fraud@discover.com"},
    "paypal": {"category": "bank_intl", "method": "email", "target": "fraud@paypal.com"},
    "stripe": {"category": "bank_intl", "method": "email", "target": "abuse@stripe.com"},
    "square": {"category": "bank_intl", "method": "email", "target": "fraud@square.com"},

    # ========== PEMERINTAH INDONESIA (15+) ==========
    "kominfo": {"category": "pemerintah", "method": "http", "url": "https://aduannomor.id/api/report"},
    "cekrekening": {"category": "pemerintah", "method": "form", "url": "https://cekrekening.id/"},
    "polri": {"category": "pemerintah", "method": "email", "target": "pengaduan@polri.go.id"},
    "kejaksaan": {"category": "pemerintah", "method": "email", "target": "pengaduan@kejaksaan.go.id"},
    "kpk": {"category": "pemerintah", "method": "email", "target": "pengaduan@kpk.go.id"},
    "ojk": {"category": "pemerintah", "method": "email", "target": "konsumen@ojk.go.id"},
    "bank_indonesia": {"category": "pemerintah", "method": "email", "target": "bantuan@bi.go.id"},
    "kemenkeu": {"category": "pemerintah", "method": "email", "target": "pengaduan@kemenkeu.go.id"},
    "kemenkumham": {"category": "pemerintah", "method": "email", "target": "pengaduan@kemenkumham.go.id"},
    "kemsos": {"category": "pemerintah", "method": "email", "target": "pengaduan@kemsos.go.id"},
    "kemendagri": {"category": "pemerintah", "method": "email", "target": "pengaduan@kemendagri.go.id"},
    "bssn": {"category": "pemerintah", "method": "email", "target": "pengaduan@bssn.go.id"},
    "bpk": {"category": "pemerintah", "method": "email", "target": "pengaduan@bpk.go.id"},
    "bpom": {"category": "pemerintah", "method": "email", "target": "pengaduan@bpom.go.id"},

    # ========== PEMERINTAH INTERNASIONAL (20+) ==========
    "ic3_fbi": {"category": "pemerintah_intl", "method": "form", "url": "https://www.ic3.gov/Home/FileComplaint"},
    "europol": {"category": "pemerintah_intl", "method": "email", "target": "info@europol.europa.eu"},
    "interpol": {"category": "pemerintah_intl", "method": "email", "target": "complaints@interpol.int"},
    "un_odc": {"category": "pemerintah_intl", "method": "email", "target": "odc@un.org"},
    "world_bank": {"category": "pemerintah_intl", "method": "email", "target": "integrity@worldbank.org"},
    "fbi": {"category": "pemerintah_intl", "method": "email", "target": "tips@fbi.gov"},
    "cia": {"category": "pemerintah_intl", "method": "email", "target": "info@cia.gov"},
    "nsa": {"category": "pemerintah_intl", "method": "email", "target": "report@nsa.gov"},
    "dhs": {"category": "pemerintah_intl", "method": "email", "target": "report@dhs.gov"},
    "us_doj": {"category": "pemerintah_intl", "method": "email", "target": "report@justice.gov"},
    "uk_nca": {"category": "pemerintah_intl", "method": "email", "target": "report@nca.gov.uk"},
    "australian_fed_police": {"category": "pemerintah_intl", "method": "email", "target": "report@afp.gov.au"},
    "canada_rcmp": {"category": "pemerintah_intl", "method": "email", "target": "report@rcmp-grc.ca"},
    "interpol_asia": {"category": "pemerintah_intl", "method": "email", "target": "asia@interpol.int"},
    "un_odc_cyber": {"category": "pemerintah_intl", "method": "email", "target": "cyber@un.org"},

    # ========== TEKNOLOGI & INTERNET (30+) ==========
    "google": {"category": "teknologi", "method": "email", "target": "report-abuse@google.com"},
    "apple": {"category": "teknologi", "method": "email", "target": "product-security@apple.com"},
    "microsoft": {"category": "teknologi", "method": "email", "target": "fraud@microsoft.com"},
    "amazon_aws": {"category": "teknologi", "method": "email", "target": "abuse@amazonaws.com"},
    "cloudflare": {"category": "teknologi", "method": "email", "target": "abuse@cloudflare.com"},
    "akamai": {"category": "teknologi", "method": "email", "target": "abuse@akamai.com"},
    "fastly": {"category": "teknologi", "method": "email", "target": "abuse@fastly.com"},
    "vercel": {"category": "teknologi", "method": "email", "target": "abuse@vercel.com"},
    "netlify": {"category": "teknologi", "method": "email", "target": "abuse@netlify.com"},
    "heroku": {"category": "teknologi", "method": "email", "target": "abuse@heroku.com"},
    "digitalocean": {"category": "teknologi", "method": "email", "target": "abuse@digitalocean.com"},
    "vultr": {"category": "teknologi", "method": "email", "target": "abuse@vultr.com"},
    "linode": {"category": "teknologi", "method": "email", "target": "abuse@linode.com"},
    "ovh": {"category": "teknologi", "method": "email", "target": "abuse@ovh.com"},
    "godaddy": {"category": "teknologi", "method": "email", "target": "abuse@godaddy.com"},
    "namecheap": {"category": "teknologi", "method": "email", "target": "abuse@namecheap.com"},
    "cloudflare_registrar": {"category": "teknologi", "method": "email", "target": "abuse@cloudflare.com"},
    "google_domains": {"category": "teknologi", "method": "email", "target": "domains-abuse@google.com"},

    # ========== HOSTING & DOMAIN (20+) ==========
    "hostgator": {"category": "hosting", "method": "email", "target": "abuse@hostgator.com"},
    "bluehost": {"category": "hosting", "method": "email", "target": "abuse@bluehost.com"},
    "siteground": {"category": "hosting", "method": "email", "target": "abuse@siteground.com"},
    "a2hosting": {"category": "hosting", "method": "email", "target": "abuse@a2hosting.com"},
    "inmotion": {"category": "hosting", "method": "email", "target": "abuse@inmotion.com"},
    "dreamhost": {"category": "hosting", "method": "email", "target": "abuse@dreamhost.com"},
    "hostinger": {"category": "hosting", "method": "email", "target": "abuse@hostinger.com"},
    "krystal": {"category": "hosting", "method": "email", "target": "abuse@krystal.co.uk"},
    "porkbun": {"category": "hosting", "method": "email", "target": "abuse@porkbun.com"},
    "namesilo": {"category": "hosting", "method": "email", "target": "abuse@namesilo.com"},

    # ========== FORUM & KOMUNITAS (15+) ==========
    "kaskus": {"category": "forum", "method": "email", "target": "report@kaskus.co.id"},
    "reddit": {"category": "forum", "method": "email", "target": "contact@reddit.com"},
    "4chan": {"category": "forum", "method": "email", "target": "abuse@4chan.org"},
    "8kun": {"category": "forum", "method": "email", "target": "abuse@8kun.net"},
    "quora": {"category": "forum", "method": "email", "target": "abuse@quora.com"},
    "stackoverflow": {"category": "forum", "method": "email", "target": "abuse@stackoverflow.com"},
    "github": {"category": "forum", "method": "email", "target": "abuse@github.com"},
    "gitlab": {"category": "forum", "method": "email", "target": "abuse@gitlab.com"},
    "bitbucket": {"category": "forum", "method": "email", "target": "abuse@bitbucket.org"},

    # ========== MEDIA INDONESIA (15+) ==========
    "detik": {"category": "media", "method": "email", "target": "redaksi@detik.com"},
    "kompas": {"category": "media", "method": "email", "target": "redaksi@kompas.com"},
    "tribun": {"category": "media", "method": "email", "target": "redaksi@tribunnews.com"},
    "cnn_indonesia": {"category": "media", "method": "email", "target": "redaksi@cnnindonesia.com"},
    "liputan6": {"category": "media", "method": "email", "target": "redaksi@liputan6.com"},
    "viva": {"category": "media", "method": "email", "target": "redaksi@viva.co.id"},
    "okezone": {"category": "media", "method": "email", "target": "redaksi@okezone.com"},
    "merdeka": {"category": "media", "method": "email", "target": "redaksi@merdeka.com"},
    "suara": {"category": "media", "method": "email", "target": "redaksi@suara.com"},
    "jawapos": {"category": "media", "method": "email", "target": "redaksi@jawapos.com"},
    "republika": {"category": "media", "method": "email", "target": "redaksi@republika.co.id"},
    "tempo": {"category": "media", "method": "email", "target": "redaksi@tempo.co.id"},
    "kumparan": {"category": "media", "method": "email", "target": "redaksi@kumparan.com"},
    "medcom": {"category": "media", "method": "email", "target": "redaksi@medcom.id"},

    # ========== MEDIA INTERNASIONAL (15+) ==========
    "bbc": {"category": "media_intl", "method": "email", "target": "contact@bbc.com"},
    "cnn": {"category": "media_intl", "method": "email", "target": "tips@cnn.com"},
    "nytimes": {"category": "media_intl", "method": "email", "target": "privacy@nytimes.com"},
    "washingtonpost": {"category": "media_intl", "method": "email", "target": "help@washpost.com"},
    "theguardian": {"category": "media_intl", "method": "email", "target": "info@theguardian.com"},
    "reuters": {"category": "media_intl", "method": "email", "target": "support@reuters.com"},
    "apnews": {"category": "media_intl", "method": "email", "target": "info@ap.org"},
    "aljazeera": {"category": "media_intl", "method": "email", "target": "contact@aljazeera.net"},
    "abc_news": {"category": "media_intl", "method": "email", "target": "contact@abc.com"},
    "cbs_news": {"category": "media_intl", "method": "email", "target": "contact@cbs.com"},
    "nbc_news": {"category": "media_intl", "method": "email", "target": "contact@nbc.com"},
    "fox_news": {"category": "media_intl", "method": "email", "target": "contact@foxnews.com"},

    # ========== DOMAIN REGISTRAR (10+) ==========
    "namecheap": {"category": "domain", "method": "email", "target": "abuse@namecheap.com"},
    "godaddy": {"category": "domain", "method": "email", "target": "abuse@godaddy.com"},
    "google_domains": {"category": "domain", "method": "email", "target": "domains-abuse@google.com"},
    "cloudflare_registrar": {"category": "domain", "method": "email", "target": "abuse@cloudflare.com"},
    "porkbun": {"category": "domain", "method": "email", "target": "abuse@porkbun.com"},
    "namesilo": {"category": "domain", "method": "email", "target": "abuse@namesilo.com"},
    "epik": {"category": "domain", "method": "email", "target": "abuse@epik.com"},
    "name.com": {"category": "domain", "method": "email", "target": "abuse@name.com"},
    "network_solutions": {"category": "domain", "method": "email", "target": "abuse@networksolutions.com"},
    "gandi": {"category": "domain", "method": "email", "target": "abuse@gandi.net"},
        # ========== FINTECH & E-WALLET (25+) ==========
    "gopay": {"category": "fintech", "method": "email", "target": "cs@gopay.co.id"},
    "ovo": {"category": "fintech", "method": "email", "target": "support@ovo.id"},
    "dana": {"category": "fintech", "method": "email", "target": "cs@dana.id"},
    "linkaja": {"category": "fintech", "method": "email", "target": "support@linkaja.com"},
    "shopeepay": {"category": "fintech", "method": "email", "target": "support@shopeepay.co.id"},
    "paypal": {"category": "fintech", "method": "email", "target": "fraud@paypal.com"},
    "stripe": {"category": "fintech", "method": "email", "target": "abuse@stripe.com"},
    "square": {"category": "fintech", "method": "email", "target": "fraud@square.com"},
    "venmo": {"category": "fintech", "method": "email", "target": "support@venmo.com"},
    "cashapp": {"category": "fintech", "method": "email", "target": "support@cash.app"},
    "zelle": {"category": "fintech", "method": "email", "target": "support@zellepay.com"},
    "wise": {"category": "fintech", "method": "email", "target": "fraud@wise.com"},
    "revolut": {"category": "fintech", "method": "email", "target": "fraud@revolut.com"},
    "skrill": {"category": "fintech", "method": "email", "target": "support@skrill.com"},
    "neteller": {"category": "fintech", "method": "email", "target": "support@neteller.com"},
    "payoneer": {"category": "fintech", "method": "email", "target": "fraud@payoneer.com"},
    "xendit": {"category": "fintech", "method": "email", "target": "support@xendit.co"},
    "midtrans": {"category": "fintech", "method": "email", "target": "support@midtrans.com"},
    "duitku": {"category": "fintech", "method": "email", "target": "cs@duitku.com"},
    "ipaymu": {"category": "fintech", "method": "email", "target": "support@ipaymu.com"},

    # ========== TRAVEL & TRANSPORTASI (20+) ==========
    "tiket": {"category": "travel", "method": "email", "target": "cs@tiket.com"},
    "traveloka": {"category": "travel", "method": "email", "target": "cs@traveloka.com"},
    "agoda": {"category": "travel", "method": "email", "target": "support@agoda.com"},
    "booking": {"category": "travel", "method": "email", "target": "fraud@booking.com"},
    "expedia": {"category": "travel", "method": "email", "target": "support@expedia.com"},
    "trivago": {"category": "travel", "method": "email", "target": "support@trivago.com"},
    "airbnb": {"category": "travel", "method": "email", "target": "fraud@airbnb.com"},
    "gojek": {"category": "travel", "method": "email", "target": "support@gojek.com"},
    "grab": {"category": "travel", "method": "email", "target": "support@grab.com"},
    "maxim": {"category": "travel", "method": "email", "target": "support@maxim.id"},
    "inDrive": {"category": "travel", "method": "email", "target": "support@indrive.com"},
    "bluebird": {"category": "travel", "method": "email", "target": "cs@bluebird.co.id"},
    "transjakarta": {"category": "travel", "method": "email", "target": "cs@transjakarta.co.id"},
    "kci": {"category": "travel", "method": "email", "target": "cs@kci.co.id"},
    "garuda": {"category": "travel", "method": "email", "target": "customercare@garuda-indonesia.com"},
    "lion": {"category": "travel", "method": "email", "target": "cs@lionair.co.id"},
    "citilink": {"category": "travel", "method": "email", "target": "customercare@citilink.co.id"},
    "batik": {"category": "travel", "method": "email", "target": "cs@batikair.com"},
    "sriwijaya": {"category": "travel", "method": "email", "target": "cs@sriwijayaair.co.id"},
    "pelni": {"category": "travel", "method": "email", "target": "cs@pelni.co.id"},

    # ========== GAME & PLATFORM GAMING (25+) ==========
    "steam": {"category": "game", "method": "email", "target": "fraud@steam.com"},
    "epic": {"category": "game", "method": "email", "target": "support@epicgames.com"},
    "riot": {"category": "game", "method": "email", "target": "support@riotgames.com"},
    "blizzard": {"category": "game", "method": "email", "target": "support@blizzard.com"},
    "ubisoft": {"category": "game", "method": "email", "target": "support@ubisoft.com"},
    "ea": {"category": "game", "method": "email", "target": "support@ea.com"},
    "rockstar": {"category": "game", "method": "email", "target": "support@rockstargames.com"},
    "nintendo": {"category": "game", "method": "email", "target": "support@nintendo.com"},
    "playstation": {"category": "game", "method": "email", "target": "support@playstation.com"},
    "xbox": {"category": "game", "method": "email", "target": "support@xbox.com"},
    "mihoyo": {"category": "game", "method": "email", "target": "support@mihoyo.com"},
    "garena": {"category": "game", "method": "email", "target": "support@garena.com"},
    "moonton": {"category": "game", "method": "email", "target": "support@moonton.com"},
    "supercell": {"category": "game", "method": "email", "target": "support@supercell.com"},
    "tencent": {"category": "game", "method": "email", "target": "support@tencent.com"},
    "netease": {"category": "game", "method": "email", "target": "support@netease.com"},
    "bandai_namco": {"category": "game", "method": "email", "target": "support@bandainamco.com"},
    "konami": {"category": "game", "method": "email", "target": "support@konami.com"},
    "capcom": {"category": "game", "method": "email", "target": "support@capcom.com"},
    "sega": {"category": "game", "method": "email", "target": "support@sega.com"},
    "square_enix": {"category": "game", "method": "email", "target": "support@square-enix.com"},

    # ========== STREAMING & HIBURAN (25+) ==========
    "netflix": {"category": "streaming", "method": "email", "target": "support@netflix.com"},
    "spotify": {"category": "streaming", "method": "email", "target": "support@spotify.com"},
    "youtube_music": {"category": "streaming", "method": "email", "target": "support@youtube.com"},
    "apple_music": {"category": "streaming", "method": "email", "target": "support@apple.com"},
    "amazon_prime": {"category": "streaming", "method": "email", "target": "support@amazon.com"},
    "disney_plus": {"category": "streaming", "method": "email", "target": "support@disneyplus.com"},
    "hbo_max": {"category": "streaming", "method": "email", "target": "support@hbomax.com"},
    "hulu": {"category": "streaming", "method": "email", "target": "support@hulu.com"},
    "paramount_plus": {"category": "streaming", "method": "email", "target": "support@paramountplus.com"},
    "peacock": {"category": "streaming", "method": "email", "target": "support@peacocktv.com"},
    "vidio": {"category": "streaming", "method": "email", "target": "cs@vidio.com"},
    "genflix": {"category": "streaming", "method": "email", "target": "support@genflix.id"},
    "iflix": {"category": "streaming", "method": "email", "target": "support@iflix.com"},
    "viki": {"category": "streaming", "method": "email", "target": "support@viki.com"},
    "we_tv": {"category": "streaming", "method": "email", "target": "support@wetv.com"},
    "iqi_yi": {"category": "streaming", "method": "email", "target": "support@iqiyi.com"},
    "bilibili": {"category": "streaming", "method": "email", "target": "support@bilibili.com"},
    "twitch": {"category": "streaming", "method": "email", "target": "support@twitch.tv"},
    "kick": {"category": "streaming", "method": "email", "target": "support@kick.com"},
    "roku": {"category": "streaming", "method": "email", "target": "support@roku.com"},
    "crunchyroll": {"category": "streaming", "method": "email", "target": "support@crunchyroll.com"},
    "funimation": {"category": "streaming", "method": "email", "target": "support@funimation.com"},

    # ========== PENDIDIKAN & KURSUS (20+) ==========
    "coursera": {"category": "pendidikan", "method": "email", "target": "support@coursera.org"},
    "udemy": {"category": "pendidikan", "method": "email", "target": "support@udemy.com"},
    "edx": {"category": "pendidikan", "method": "email", "target": "support@edx.org"},
    "skillshare": {"category": "pendidikan", "method": "email", "target": "support@skillshare.com"},
    "duolingo": {"category": "pendidikan", "method": "email", "target": "support@duolingo.com"},
    "ruangguru": {"category": "pendidikan", "method": "email", "target": "cs@ruangguru.com"},
    "zenius": {"category": "pendidikan", "method": "email", "target": "support@zenius.net"},
    "pahamify": {"category": "pendidikan", "method": "email", "target": "support@pahamify.com"},
    "kelas": {"category": "pendidikan", "method": "email", "target": "cs@kelas.com"},
    "quipper": {"category": "pendidikan", "method": "email", "target": "support@quipper.com"},
    "scholarship": {"category": "pendidikan", "method": "email", "target": "support@scholarship.com"},
    "go_course": {"category": "pendidikan", "method": "email", "target": "support@gocourse.id"},
    "dicoding": {"category": "pendidikan", "method": "email", "target": "support@dicoding.com"},
    "code_academy": {"category": "pendidikan", "method": "email", "target": "support@codecademy.com"},
    "freecodecamp": {"category": "pendidikan", "method": "email", "target": "support@freecodecamp.org"},
    "khan_academy": {"category": "pendidikan", "method": "email", "target": "support@khanacademy.org"},
    "progate": {"category": "pendidikan", "method": "email", "target": "support@progate.com"},

    # ========== JASA & MARKETPLACE JASA (20+) ==========
    "fiverr": {"category": "jasa", "method": "email", "target": "support@fiverr.com"},
    "upwork": {"category": "jasa", "method": "email", "target": "support@upwork.com"},
    "freelancer": {"category": "jasa", "method": "email", "target": "support@freelancer.com"},
    "sribu": {"category": "jasa", "method": "email", "target": "cs@sribu.com"},
    "projects": {"category": "jasa", "method": "email", "target": "support@projects.co.id"},
    "taskrabbit": {"category": "jasa", "method": "email", "target": "support@taskrabbit.com"},
    "thumbtack": {"category": "jasa", "method": "email", "target": "support@thumbtack.com"},
    "care.com": {"category": "jasa", "method": "email", "target": "support@care.com"},
    "guru": {"category": "jasa", "method": "email", "target": "support@guru.com"},
    "peopleperhour": {"category": "jasa", "method": "email", "target": "support@peopleperhour.com"},
    "toptal": {"category": "jasa", "method": "email", "target": "support@toptal.com"},
    "truelancer": {"category": "jasa", "method": "email", "target": "support@truelancer.com"},

    # ========== CRYPTO & EXCHANGE (15+) ==========
    "binance": {"category": "crypto", "method": "email", "target": "fraud@binance.com"},
    "coinbase": {"category": "crypto", "method": "email", "target": "support@coinbase.com"},
    "indodax": {"category": "crypto", "method": "email", "target": "support@indodax.com"},
    "tokocrypto": {"category": "crypto", "method": "email", "target": "support@tokocrypto.com"},
    "bittrex": {"category": "crypto", "method": "email", "target": "support@bittrex.com"},
    "kraken": {"category": "crypto", "method": "email", "target": "support@kraken.com"},
    "gemini": {"category": "crypto", "method": "email", "target": "support@gemini.com"},
    "bybit": {"category": "crypto", "method": "email", "target": "support@bybit.com"},
    "okx": {"category": "crypto", "method": "email", "target": "support@okx.com"},
    "huobi": {"category": "crypto", "method": "email", "target": "support@huobi.com"},
    "ftx": {"category": "crypto", "method": "email", "target": "support@ftx.com"},
    "kucoin": {"category": "crypto", "method": "email", "target": "support@kucoin.com"},
    "bitfinex": {"category": "crypto", "method": "email", "target": "support@bitfinex.com"},
    "bitstamp": {"category": "crypto", "method": "email", "target": "support@bitstamp.com"},
    "crypto_com": {"category": "crypto", "method": "email", "target": "support@crypto.com"},

    # ========== MARKETPLACE ALTERNATIF (15+) ==========
    "carousell": {"category": "marketplace", "method": "email", "target": "support@carousell.com"},
    "olx": {"category": "marketplace", "method": "email", "target": "support@olx.co.id"},
    "mudah": {"category": "marketplace", "method": "email", "target": "support@mudah.my"},
    "webike": {"category": "marketplace", "method": "email", "target": "support@webike.id"},
    "sepeda": {"category": "marketplace", "method": "email", "target": "support@sepeda.id"},
    "carsome": {"category": "marketplace", "method": "email", "target": "support@carsome.id"},
    "mobil123": {"category": "marketplace", "method": "email", "target": "cs@mobil123.com"},
    "rumah123": {"category": "marketplace", "method": "email", "target": "cs@rumah123.com"},
    "olx_autos": {"category": "marketplace", "method": "email", "target": "support@olxautos.com"},
    "gumtree": {"category": "marketplace", "method": "email", "target": "support@gumtree.com"},
    "craigslist": {"category": "marketplace", "method": "email", "target": "abuse@craigslist.org"},
    "facebook_marketplace": {"category": "marketplace", "method": "email", "target": "abuse@facebook.com"},
    "mercari": {"category": "marketplace", "method": "email", "target": "support@mercari.com"},
    "poshmark": {"category": "marketplace", "method": "email", "target": "support@poshmark.com"},
    "depop": {"category": "marketplace", "method": "email", "target": "support@depop.com"},

    # ========== APLIKASI KENCAN & SOSIAL LAIN (10+) ==========
    "badoo": {"category": "sosial_media", "method": "email", "target": "support@badoo.com"},
    "feeld": {"category": "sosial_media", "method": "email", "target": "support@feeld.co"},
    "her": {"category": "sosial_media", "method": "email", "target": "support@her.com"},
    "lex": {"category": "sosial_media", "method": "email", "target": "support@lex.lgbt"},
    "doublelist": {"category": "sosial_media", "method": "email", "target": "support@doublelist.com"},

    # ========== DUKUNGAN TEKNIS (10+) ==========
    "mozilla": {"category": "teknologi", "method": "email", "target": "abuse@mozilla.com"},
    "opera": {"category": "teknologi", "method": "email", "target": "abuse@opera.com"},
    "brave": {"category": "teknologi", "method": "email", "target": "abuse@brave.com"},
    "vivaldi": {"category": "teknologi", "method": "email", "target": "abuse@vivaldi.com"},
    "tor": {"category": "teknologi", "method": "email", "target": "abuse@torproject.org"},
    "proton": {"category": "teknologi", "method": "email", "target": "abuse@proton.me"},
    "tutanota": {"category": "teknologi", "method": "email", "target": "abuse@tutanota.com"},
    "mailbox": {"category": "teknologi", "method": "email", "target": "abuse@mailbox.org"},
    "startmail": {"category": "teknologi", "method": "email", "target": "abuse@startmail.com"},
    "posteo": {"category": "teknologi", "method": "email", "target": "abuse@posteo.de"},

    # ========== ASURANSI & INVESTASI (10+) ==========
    "bni_life": {"category": "keuangan", "method": "email", "target": "cs@bnilife.co.id"},
    "aia": {"category": "keuangan", "method": "email", "target": "support@aia.com"},
    "prudential": {"category": "keuangan", "method": "email", "target": "support@prudential.com"},
    "allianz": {"category": "keuangan", "method": "email", "target": "support@allianz.com"},
    "sequis": {"category": "keuangan", "method": "email", "target": "support@sequis.com"},
    "manulife": {"category": "keuangan", "method": "email", "target": "support@manulife.com"},
    "axa": {"category": "keuangan", "method": "email", "target": "support@axa.com"},
    "saham": {"category": "keuangan", "method": "email", "target": "support@saham.com"},
    "aplikasi": {"category": "keuangan", "method": "email", "target": "support@aplikasi.com"},
    "fund": {"category": "keuangan", "method": "email", "target": "support@fund.com"},
}

# ===== Fungsi tambahan untuk main.py =====

def get_categories():
    """Mengembalikan daftar kategori unik dari semua provider"""
    categories = set()
    for info in PROVIDERS.values():
        categories.add(info.get("category", "umum"))
    return sorted(list(categories))

def get_providers_by_category(category):
    """Mengembalikan dictionary provider yang termasuk dalam kategori tertentu"""
    result = {}
    for name, info in PROVIDERS.items():
        if info.get("category") == category:
            result[name] = info
    return result
